/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wingsnepal.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Aayush Kharel
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword(String email) {
        initComponents();
        scaleImage();
        setResizable(false);         //Disable maximize button
        setLocationRelativeTo(null); //Center window
    }
        public void scaleImage(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagepicker/Aeroplane Image 2.jpg"));
        //scaling image to fit in the hlabel.
        Image img1 = icon.getImage();
        Image imgScale = img1.getScaledInstance(BgLabel.getWidth(), BgLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        BgLabel.setIcon(scaledIcon);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResetPanel = new javax.swing.JPanel();
        ResetPasswordLabel = new javax.swing.JLabel();
        NewPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        NewPasswordTextField = new javax.swing.JPasswordField();
        ConfirmPasswordTextField = new javax.swing.JPasswordField();
        OTPLabel = new javax.swing.JLabel();
        OTPTextField = new javax.swing.JTextField();
        ReseButton = new javax.swing.JButton();
        BgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResetPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        ResetPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ResetPasswordLabel.setText("Reset Password");

        NewPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        NewPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        NewPasswordLabel.setText("New Password");

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordLabel.setText("Confirm Password");

        OTPLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        OTPLabel.setForeground(new java.awt.Color(255, 255, 255));
        OTPLabel.setText("Enter OTP ");

        OTPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPTextFieldActionPerformed(evt);
            }
        });

        ReseButton.setBackground(new java.awt.Color(0, 102, 153));
        ReseButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        ReseButton.setForeground(new java.awt.Color(255, 255, 255));
        ReseButton.setText("Reset");
        ReseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResetPanelLayout = new javax.swing.GroupLayout(ResetPanel);
        ResetPanel.setLayout(ResetPanelLayout);
        ResetPanelLayout.setHorizontalGroup(
            ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(NewPasswordLabel)
                    .addComponent(OTPLabel))
                .addGap(18, 18, 18)
                .addGroup(ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(NewPasswordTextField)
                    .addComponent(ConfirmPasswordTextField)
                    .addComponent(OTPTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResetPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(ResetPasswordLabel)
                .addGap(84, 84, 84))
        );
        ResetPanelLayout.setVerticalGroup(
            ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ResetPasswordLabel)
                .addGap(60, 60, 60)
                .addGroup(ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OTPLabel)
                    .addComponent(OTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPasswordLabel)
                    .addComponent(NewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(ReseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(ResetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 350, 370));
        ResetPanel.setBackground(new java.awt.Color(102,102,102,80));

        BgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/Aeroplane Image 2.jpg"))); // NOI18N
        BgLabel.setText("BgLabel");
        getContentPane().add(BgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OTPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTPTextFieldActionPerformed

    private void ReseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReseButtonActionPerformed
        // handlePasswordReset(); // REMOVED - now handled by controller
    }//GEN-LAST:event_ReseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResetPassword view = new ResetPassword("");
                new controller.ResetPasswordController(view, "").open();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgLabel;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel NewPasswordLabel;
    private javax.swing.JPasswordField NewPasswordTextField;
    private javax.swing.JLabel OTPLabel;
    private javax.swing.JTextField OTPTextField;
    private javax.swing.JButton ReseButton;
    private javax.swing.JPanel ResetPanel;
    private javax.swing.JLabel ResetPasswordLabel;
    // End of variables declaration//GEN-END:variables
    
    // Getter methods for controller access
    public javax.swing.JButton getReseButton() {
        return ReseButton;
    }
    
    public javax.swing.JTextField getOTPTextField() {
        return OTPTextField;
    }
    
    public javax.swing.JPasswordField getNewPasswordTextField() {
        return NewPasswordTextField;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordTextField() {
        return ConfirmPasswordTextField;
    }
}
